version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/bochor-backend:latest  # Nombre con el usuario de Docker Hub
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/bochor-frontend:latest  # Nombre con el usuario de Docker Hub
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
