version: '3.8'

services:
  backend:
    image: mesvirtual/bochor-backend:latest
    platform: "linux/amd64"
    platform: "linux/arm64"

    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: mesvirtual/bochor-frontend:latest
    platform: "linux/amd64"
    platform: "linux/arm64"
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
