version: '3.8'

services:
  backend:
    image: bochor-backend:latest  # Sin interpolación directa
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: bochor-frontend:latest  # Sin interpolación directa
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
