version: '3.8'

services:
  backend:
    image: mesvirtual/bochor-backend:latest
    build:
      context: ./Back
      dockerfile: Dockerfile
    platform: "linux/arm64/v8"  # Plataforma en formato string
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: mesvirtual/bochor-frontend:latest
    build:
      context: ./Front
      dockerfile: Dockerfile
    platform: "linux/arm64/v8"  # Plataforma en formato string
    ports:
      - "80:80"
    restart: always
