version: '3.8'

services:
  backend:
    image: mesvirtual/bochor-backend:latest  # Imagen desde Docker Hub
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    image: mesvirtual/bochor-frontend:latest  # Imagen desde Docker Hub
    ports:
      - "80:80"
    restart: always
