name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Push Docker images
        run: |
          docker push bochor-frontend
          docker push bochor-backend

      - name: SSH into Raspberry Pi and pull the latest Docker images
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.RASPBERRY_PI_HOST }}
          username: ${{ secrets.RASPBERRY_PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/mi-carpeta-de-proyecto
            docker pull bochor-frontend
            docker pull bochor-backend
            docker-compose down
            docker-compose up -d
