name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: |
          # Construir las imágenes utilizando Docker Compose
          docker-compose -f docker-compose.yml build

      - name: Push Docker images
        run: |
          # Etiquetar las imágenes y subirlas a Docker Hub
          docker tag bochor-frontend:latest ${{ secrets.DOCKER_USERNAME }}/bochor-frontend:latest
          docker tag bochor-backend:latest ${{ secrets.DOCKER_USERNAME }}/bochor-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bochor-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bochor-backend:latest

      - name: Restart Containers
        run: |
          # Detener y levantar los contenedores con Docker Compose
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d
