name: Build and Deploy Docker Containers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables for Docker Compose
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV

      - name: Get commit hash
        id: commit
        run: echo "::set-output name=commit::$(git rev-parse --short HEAD)"

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build --build-arg DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

      - name: List Docker images
        run: docker images

      - name: Tag Docker images with commit hash
        run: |
          docker tag bochor-frontend:latest ${{ secrets.DOCKER_USERNAME }}/bochor-frontend:${{ steps.commit.outputs.commit }}
          docker tag bochor-backend:latest ${{ secrets.DOCKER_USERNAME }}/bochor-backend:${{ steps.commit.outputs.commit }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/bochor-frontend:${{ steps.commit.outputs.commit }}
          docker push ${{ secrets.DOCKER_USERNAME }}/bochor-backend:${{ steps.commit.outputs.commit }}
